version: "3.1"

services:
  test-mongodb-taas:
    image: mongo
    container_name: test-mongodb-taas
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: myusername # Set your desired username
      MONGO_INITDB_ROOT_PASSWORD: mypassword # Set your desired password
    ports:
      - "27017:27017" # Expose MongoDB port
    networks:
      - test-backend

  test-redis-taas:
    image: "redis:latest"
    restart: always
    ports:
      - "6381:6379" # Make host port 6381 to avoid conflict with local redis service and development one. Mapped to 6379 on the container.
    networks:
      - test-backend
    command: redis-server --appendonly yes # Enable append-only file for persistence

  test-taas:
    image: "node:20"
    working_dir: "/app"
    volumes:
      - "./:/app"
    build:
      context: .
    ports:
      - "8001:8000"
    depends_on:
      - test-mongodb-taas
      - test-redis-taas
    environment:
      NODE_ENV: "test"
      SECRET: ${SECRET}
      REDIS_HOST: "test-redis-taas"
      REDIS_PORT: "6379"
      EMAIL: ${EMAIL}
      APP_URL: ${APP_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      MONGO: mongodb://myusername:mypassword@test-mongodb-taas:27017/test-mongodb-taas?authSource=admin
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
    command: "yarn dev"
    networks:
      - test-backend

networks:
  test-backend:
    driver: bridge
