# fly.toml app configuration file generated for taas-backend-solitary-waterfall-8410 on 2024-04-29T12:39:26-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'taas-backend'
primary_region = 'bos'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
